const METRIC_DISPLAY_COLORS = {
  BUSINESS_IMPRESSIONS_DESKTOP_MAPS: "#9600ff",
  BUSINESS_IMPRESSIONS_DESKTOP_SEARCH: "#4900ff",
  BUSINESS_IMPRESSIONS_MOBILE_MAPS: "#00b8ff",
  BUSINESS_IMPRESSIONS_MOBILE_SEARCH: "#00fff9",
  BUSINESS_CONVERSATIONS: "#ff00c1",
  BUSINESS_DIRECTION_REQUESTS: "#9600ff",
  CALL_CLICKS: "#4900ff",
  WEBSITE_CLICKS: "#00b8ff",
  BUSINESS_BOOKINGS: "#00fff9",
  BUSINESS_FOOD_ORDERS: "#ff00c1",
  BUSINESS_FOOD_MENU_CLICKS: "#9600ff",
};

const METRIC_NAMES = [
  "BUSINESS_IMPRESSIONS_DESKTOP_MAPS",
  "BUSINESS_IMPRESSIONS_DESKTOP_SEARCH",
  "BUSINESS_IMPRESSIONS_MOBILE_MAPS",
  "BUSINESS_IMPRESSIONS_MOBILE_SEARCH",
  "BUSINESS_CONVERSATIONS",
  "BUSINESS_DIRECTION_REQUESTS",
  "CALL_CLICKS",
  "WEBSITE_CLICKS",
  "BUSINESS_BOOKINGS",
  "BUSINESS_FOOD_ORDERS",
  "BUSINESS_FOOD_MENU_CLICKS",
];

export { METRIC_DISPLAY_COLORS, METRIC_NAMES };
